server:
  port: 80
  servlet:
    context-path: /sp3    # application path


# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/warehouse?useSSL=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123


springdoc:
  api-docs:
    enabled: true # 关闭OpenApi接口
  swagger-ui:
    enabled: true # 关闭swagger界面

